---
  - name: Ensure to cleanup ports and services before adding hosts.
    hosts: k8sclusternodes
    gather_facts: false
    roles:
      - role: k8s-hosts
        vars:
          cleanup: true
  - name: Add k8s-hosts into cluster and install bundle.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-hosts
        vars:
          addhosts: true

  - name: Delete k8s-hosts from cluster.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-hosts
        vars:
          deletehosts: false
          delete_pools:
            - host: 10.1.10.22
