---
  - name: Prepare nodes before installing software.
    # --erase option. Erase BlueData Software on the host. When
    # invoked on the controller this will erase the
    # software in any workers as well.
    hosts: controller
    gather_facts: false
    roles:
      - role: uninstall-bds
        vars:
          uninstall: yes

  - name: Prepare nodes before installing software.
    # --erase option. is not delete old yum repo's
    hosts: allnodes:!controller
    gather_facts: false
    roles:
      - role: uninstall-bds
        vars:
          cleanup_repo: yes